config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :songs, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Songbooks</h1>
<%= link_to "Add a Song", new_song_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songbooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/new.html.erb
<h1>New Song</h1>
<% if @song.errors.any? %>
  <div>
    <h3><%= flash[:error] %></h3>
    <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>

<% end %>
<%= form_with model: @song do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :artist %>
  <%= form.text_field :artist %>
  <%= form.label :body %>
  <%= form.text_area :body, size: "60x10" %>
  <%= form.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<h2><%= @song.artist %></h2>
<pre><%= @song.body %></pre>